name: Perform Lint Checks on Frontend

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "frontend_ci"
  frontend_ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Install dependencies
      - name: Install dependencies
        run:  yarn --cwd ./frontend
        
      #Lint Check
      - name: Run lint for frontend
        working-directory: ./frontend
        run: yarn lint
